-- Your SQL goes here
ALTER TABLE users
ADD COLUMN password VARCHAR(255) NOT NULL,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD COLUMN modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;